version: "3.9"
services:
  app:
    hostname: localhost
    build: 
      dockerfile: build/Dockerfile
      context: .
    image: sebin10/go-notebook
    volumes:
      - .:/app
    ports:
      - 8080:8080